# Generated by Django 4.1.6 on 2023-02-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('made_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchase', models.DateField()),
                ('date_sale', models.DateField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moto.bike')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moto.owner')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motocycle', to='moto.owner'),
        ),
        migrations.AddField(
            model_name='bike',
            name='previous_owners',
            field=models.ManyToManyField(related_name='motocycles', through='moto.Ownership', to='moto.owner'),
        ),
    ]
