# Generated by Django 4.1.6 on 2023-02-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_alter_bike_current_owner_alter_bike_previous_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_bikes', to='moto.owner'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='previous_owners',
            field=models.ManyToManyField(related_name='previous_bikes', through='moto.Ownership', to='moto.owner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.bike'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.owner'),
        ),
    ]
